# Generated by Django 6.0.3 on 2026-03-24 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpl', '0001_initial'),
        ('factories', '0005_alter_factory_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpl',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factories.factory'),
        ),
    ]
