# Generated by Django 6.0.3 on 2026-03-16 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dpl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joia_code', models.CharField(max_length=50)),
                ('showroom_color', models.CharField(max_length=50)),
                ('lot_number', models.IntegerField()),
                ('roll_number', models.IntegerField()),
                ('qty_kg', models.FloatField()),
                ('qty_mtr', models.FloatField()),
                ('status', models.CharField(choices=[('incoming', 'Incoming'), ('actual', 'Actual'), ('reserved', 'Reserved')], default='incoming', max_length=20)),
                ('dpl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpl.dpl')),
            ],
        ),
    ]
