# Generated by Django 6.0.3 on 2026-03-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='qty_mtr',
            new_name='qty_m',
        ),
    ]
