# Generated by Django 6.0.3 on 2026-03-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_qty_mtr_stock_qty_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='style_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
