# Generated by Django 6.0.3 on 2026-03-23 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_style_number'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.color'),
        ),
    ]
