# Generated by Django 6.0.3 on 2026-03-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_stock_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='color_code',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='stock',
            name='color_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='showroom_color',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
