# Generated by Django 6.0.3 on 2026-03-28 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stock_color_code_stock_color_name_and_more'),
        ('products', '0004_remove_color_showroom_color_alter_color_color_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.product'),
        ),
    ]
