# Generated by Django 6.0.3 on 2026-03-29 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stock_product'),
        ('order', '0003_rename_style_number_quotationline_joia_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_stocks', to='order.quotation'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='status',
            field=models.CharField(choices=[('incoming', 'Incoming'), ('actual', 'Actual'), ('reserved', 'Reserved'), ('backorder', 'Backorder')], default='incoming', max_length=20),
        ),
    ]
