# Generated by Django 6.0.3 on 2026-03-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stock_quotation_alter_stock_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='lot_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='qty_kg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='qty_m',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='roll_number',
            field=models.IntegerField(default=0),
        ),
    ]
