# Generated by Django 6.0.3 on 2026-03-30 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpl', '0002_alter_dpl_factory'),
        ('inventory', '0009_alter_stock_lot_number_alter_stock_qty_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='dpl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dpl.dpl'),
        ),
    ]
