# Generated by Django 6.0.3 on 2026-04-02 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_stock_dpl'),
        ('order', '0005_alter_quotation_vat_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='quotation_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.quotationline'),
        ),
    ]
