# Generated by Django 6.0.3 on 2026-04-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_stock_quotation_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='unit',
            field=models.CharField(choices=[('m', 'Meter'), ('kg', 'Kilogram')], default='m', max_length=10),
        ),
    ]
