# Generated by Django 6.0.3 on 2026-03-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='code',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
