# Generated by Django 6.0.3 on 2026-04-05 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales_Order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorderline',
            name='status',
        ),
    ]
