# Generated by Django 6.0.3 on 2026-04-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales_Order', '0002_remove_salesorderline_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
