# Generated by Django 6.0.3 on 2026-04-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales_Order', '0003_salesorderline_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderline',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
