# Generated by Django 6.0.3 on 2026-04-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales_Order', '0004_salesorderline_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
