# Generated by Django 6.0.3 on 2026-03-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0003_alter_factory_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
