# Generated by Django 6.0.3 on 2026-03-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0004_alter_factory_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
