# Generated by Django 6.0.3 on 2026-03-20 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0006_alter_customer_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.IntegerField(blank=True, unique=True)),
                ('vat_percentage', models.FloatField(default=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_number', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('rolls', models.IntegerField()),
                ('qty_m', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='order.quotation')),
            ],
        ),
    ]
