# Generated by Django 6.0.3 on 2026-03-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationline',
            name='color',
        ),
        migrations.AddField(
            model_name='quotationline',
            name='color_code',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='color_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
