# Generated by Django 6.0.3 on 2026-03-29 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_quotationline_color_quotationline_color_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationline',
            old_name='style_number',
            new_name='joia_code',
        ),
    ]
