# Generated by Django 6.0.3 on 2026-04-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_quotation_notes_alter_quotation_quotation_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=14, max_digits=5),
        ),
    ]
