# Generated by Django 6.0.3 on 2026-04-03 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_quotation_vat_percentage'),
        ('products', '0004_remove_color_showroom_color_alter_color_color_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
