# Generated by Django 6.0.3 on 2026-03-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_color_color_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='showroom_color',
        ),
        migrations.AlterField(
            model_name='color',
            name='color_name',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
